# 워크플로우의 이름
name: Docker Image CI

# 워크플로우가 실행될 조건 설정
on:
  push:
    branches: [ "main" ] # main 브랜치에 push될 때 실행

# 실행될 작업(job) 정의
jobs:
  build:
    runs-on: ubuntu-latest # 작업이 실행될 가상 환경

    steps:
      # 1. 리포지토리의 코드를 가상 환경으로 가져옴
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Docker Hub에 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ssanaimandu/helloworld:latest # Docker Hub 사용자명과 이미지 태그를 입력하세요.
